# fly.toml app configuration file generated for ridery-demo-project on 2024-06-18T21:22:55-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ridery-demo-project'
primary_region = 'eze'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
